version: "3.8"

services:
  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'webmaster@deroliver.me'
      HTTP_SERVER_NAME: 'deroliver.me'
      HTTPS_SERVER_NAME: 'deroliver.me'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - '/htdocs'
    ports:
      - '8200:80'
      - '8201:443'
    restart: unless-stopped
    user: apache:apache
    # read_only: true
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8
    environment:
        MYSQL_ROOT_PASSWORD: xeFgUGb5mPPn5q2d
    ports:
        - 3306:3306
